---
title: "Fantasy land"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { icon: "fa-question-circle", href: "https://water.noaa.gov/about/nwm", align: right }
    theme: flatly
    orientation: rows
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(shiny)
library(flexdashboard)
library(shinyWidgets)
library(shinycustomloader)

library(nflfastR)
library(DT)
library(plotly)

library(ggplot2)
library(dplyr)
library(tidyr)
library(DT)
library(plotly)
library(highcharter)
library(billboarder)

source('helper.R')
```

```{r context="server"}
 # season <<- reactive({
     # season <- load_data(as.numeric(input$seasonDropdown))
 # })
# season <- reactiveValues()
season <<- reactive({
  dataset <- load_data(as.numeric(input$seasonDropdown))
})

player1 <- reactive({
  df2 <- get_player_data(season(), input$playerSearch, input$weekRange[1], input$weekRange[2])
})

```

Player stats {data-icon="fa-tint"}
====================================

Inputs {.sidebar}
-------------------------------------

### Filters
```{r}
# dqshiny::autocomplete_input("auto", "Search for a County:",
#                                 value = "",
#                                 max_options = 5,
#                                 options = list(season()$full_name))

selectInput("seasonDropdown",
            label = "Season", 
            selected = 2020,
            choices = c("All", 2020:1999))

selectInput("positionDropdown",
            label = "Position", 
            choices = c("All", "QB", "RB", "WR", "TE"))

uiOutput("playerSelector")

selectInput("variableDropdown",
            label = "Variable", 
            choices = c(NULL, "Air yards", "Targets/Receptions", "Yards per carry"))

# Input: Specification of range within an interval ----
sliderInput("weekRange", "Week",
                  min = 1, max = 16,
                  value = c(1, 16))

verbatimTextOutput("seasonDropdownText")

verbatimTextOutput("positionDropdownText")

verbatimTextOutput("playerSearchText")

verbatimTextOutput("weekRangeText")

verbatimTextOutput("variableDropText")
```

```{r context = "server"}
# TESTING INPUTS + ACTION BUTTON REACTIVITY
seasonText <- eventReactive(input$submitButton, {
    paste0("Season: ", input$seasonDropdown)
  })

output$seasonDropdownText <- renderText({
   seasonText()
  })

positionText <- eventReactive(input$submitButton, {
    paste0("Position: ", input$positionDropdown)
  })
  
output$positionDropdownText <- renderText({
   positionText()
  })

playerText <- eventReactive(input$submitButton, {
    paste0("Player: ", input$playerSearch)
  })
  
output$playerSearchText <- renderText({
   playerText()
  })

weekRangeText <- eventReactive(input$submitButton, {
    paste0("Week: ", input$weekRange[1], input$weekRange[2])
  })
  
output$weekRangeText <- renderText({
   weekRangeText()
  })
```

```{r context = "server"}
# playerVariable <- eventReactive(input$submitButton, {
#   if(input$variableDropdown == "Air yards") {
#           df <- season()
#      
#           df1 <- player1()
#           # pivot longer for billboarder plot
#           air_yards <- df1 %>%
#             pivot_longer(c(33:34, 52), names_to = "air_yards_str", values_to = "air_yards_val")
# 
#           billboarder::billboarder() %>%
#               bb_barchart(data = air_yards,
#                   mapping = bbaes(x = week, y = air_yards_val, group = air_yards_str))
#           
#   } else if (input$variableDropdown == "Targets/Receptions") {
#         df <- season()
#         df1 <- player1()
#         # pivot longer for billboarder plot
#         df1 <- df1 %>%
#             pivot_longer(29:28, names_to = "rcpt_str", values_to = "rcpt_val")
# 
#         billboarder() %>%
#           bb_barchart(data = df1,
#                       mapping = bbaes(x = week, y = rcpt_val, group = rcpt_str))
#   } else if (input$variableDropdown == "Yards per carry") {
#         df <- season()
#         df1 <- player1()
#         
#         df1 <- df1 %>%
#           mutate(fpts_per_touch = fpts_hppr/(receptions + carries)) %>%
#           pivot_longer(c(62, 63), names_to = "ypc_str", values_to = "ypc_val")
#         
#         billboarder() %>%
#           bb_linechart(data = df1,
#                 mapping = bbaes(x = week, y = ypc_val, group = ypc_str))
#         # rb1 <- get_player_data(season, "Jonathan Taylor", 1, 16)
#         # rb1 <- rb1 %>%
#         #   mutate(fpts_per_touch = fpts_hppr/(receptions + carries)) %>%
#         #   pivot_longer(c(62, 63), names_to = "ypc_str", values_to = "ypc_val")
#         # tmp1 <- rb1 %>% select(1:7, 59:63)
#   }
# })
#   
# output$variableGraph <- renderBillboarder({
#    playerVariable()
#   })
```

### **Submit**
```{r}
shiny::actionButton("submitButton", label = "Enter", icon("search"))
```

Row
--------------------------------------------------
### Game log
```{r}
plotlyOutput("gamelogGraph")
```

```{r context = "server"}
gamelogData <- eventReactive(input$submitButton, {
  if(is.null(input$playerSearch)) {
    NULL
  } else if (!is.null(input$variableDropdown)) {
    df <- season()
    # df <- get_player_data(df, input$playerSearch, input$weekRange[1], input$weekRange[2])
    df1 <- player1()
    make_player_plot(df1)
  }
})

output$gamelogGraph <- renderPlotly({
  gamelogData()
})
```


Row {.tabset}
--------------------------------------------------
### Variable input 
```{r}
billboarderOutput("playerVarGraph")
```

```{r context = "server"}
playerVarData <- eventReactive(input$submitButton, {
  if(input$variableDropdown == "Air yards") {
          df <- season()
     
          df1 <- player1()
          # pivot longer for billboarder plot
          air_yards <- df1 %>%
            pivot_longer(c(33:34, 52), names_to = "air_yards_str", values_to = "air_yards_val")

          billboarder::billboarder() %>%
              bb_barchart(data = air_yards,
                  mapping = bbaes(x = week, y = air_yards_val, group = air_yards_str))
          
  } else if (input$variableDropdown == "Targets/Receptions") {
        df <- season()
        df1 <- player1()
        # pivot longer for billboarder plot
        df1 <- df1 %>%
            pivot_longer(29:28, names_to = "rcpt_str", values_to = "rcpt_val")

        billboarder() %>%
          bb_barchart(data = df1,
                      mapping = bbaes(x = week, y = rcpt_val, group = rcpt_str))
  } else if (input$variableDropdown == "Yards per carry") {
        df <- season()
        df1 <- player1()
        
        df1 <- df1 %>%
          mutate(fpts_per_touch = fpts_hppr/(receptions + carries)) %>%
          pivot_longer(c(62, 63), names_to = "ypc_str", values_to = "ypc_val")
        
        billboarder() %>%
          bb_linechart(data = df1,
                mapping = bbaes(x = week, y = ypc_val, group = ypc_str))
        # rb1 <- get_player_data(season, "Jonathan Taylor", 1, 16)
        # rb1 <- rb1 %>%
        #   mutate(fpts_per_touch = fpts_hppr/(receptions + carries)) %>%
        #   pivot_longer(c(62, 63), names_to = "ypc_str", values_to = "ypc_val")
        # tmp1 <- rb1 %>% select(1:7, 59:63)
  }
})
  
output$playerVarGraph <- renderBillboarder({
   playerVarData()
  })
```

### League rankings
```{r}
highchartOutput("leagueRankGraph")
```

```{r context = "server"}
leagueRankData <- eventReactive(input$submitButton, {
  if(input$variableDropdown == "Air yards") {
          df1 <- season()
          df2 <- player1()
          
          rank_airyards <- df1 %>%
            filter(position == df2$position[1]) %>%
            group_by(player_id) %>%
            add_count(name = "count1") %>%
            filter(week >= input$weekRange[1], week <= input$weekRange[2]) %>%
            add_count(name = "count2") %>%
            mutate(tot_fpts = sum(fpts_hppr),
                   tot_tds = sum(rushing_tds) + sum(passing_tds) + sum(receiving_tds) + sum(special_teams_tds),
                   tot_recept = sum(receptions),
                   tot_targ = sum(targets),
                   tot_carries = sum(carries),
                   tot_touch = tot_recept+ tot_carries,
                   fpts_pg = tot_fpts/count2,
                   targ_pg = tot_targ/count2,
                   recept_pg = tot_recept/count2,
                   carries_pg = tot_carries/count2,
                   airyards_pg = sum(receiving_air_yards)/count2,
                   fpts_pt = fpts_pg/(recept_pg + carries_pg),
                   yards_pg = (sum(rushing_yards) + sum(receiving_yards) + sum(passing_yards))/count2,
                   passyards_pg = sum(passing_yards)/count2,
                   td_int_ratio = sum(passing_tds)/sum(interceptions)) %>%
            slice(n = 1) %>%
            # filter(tot_touch >= 100 | tot_recept >=60) %>%
            arrange(-airyards_pg) %>%
            ungroup() %>%
            slice(n = 1:36)

            billboarder() %>%
                bb_barchart(data = rank_airyards,
                          mapping = bbaes(x = full_name, y = airyards_pg)) %>%
                bb_title(text = "AIR YARDS PER GAME") %>%
                bb_axis(y = list(label = list(text = "YARDS", position = "middle")))
          
  } else if (input$variableDropdown == "Targets/Receptions") {
        df1 <- season()
        df2 <- player1()
  
        rank_targ <- df1 %>%
            filter(position == df2$position[1]) %>%
            group_by(player_id) %>%
            add_count(name = "count1") %>%
            # filter(week >= 1, week <= 16) %>%
            filter(week >= input$weekRange[1], week <= input$weekRange[2]) %>%
            add_count(name = "count2") %>%
            mutate(tot_fpts = sum(fpts_hppr),
                   tot_tds = sum(rushing_tds) + sum(passing_tds) + sum(receiving_tds) + sum(special_teams_tds),
                   tot_recept = sum(receptions),
                   tot_targ = sum(targets),
                   fpts_pg = tot_fpts/count2,
                   targ_pg = tot_targ/count2,
                   recept_pg = tot_recept/count2) %>%
            slice(n = 1) %>%
            arrange(-recept_pg) %>%
            ungroup() %>%
            # mutate(rank = 1:n(),
            #        max = max(recept_pg),
            #        med = median(recept_pg),
            #        min = min(recept_pg)) %>%
            slice(n = 1:36)
        
        highchart() %>%
            hc_add_series(rank_targ, type = "column", hcaes(x = full_name, y = recept_pg)) %>%
            hc_add_series(rank_targ, type = "column", hcaes(x = full_name, y = targ_pg)) %>%
            hc_chart(plotBorderWidth = 1, plotBorderColor = '#b4b4b4', height = '100%') %>%
            hc_xAxis(categories = rank_targ$full_name)
      # rank_targ <- rename(rank_targ, "Targets per game" = targ_pg, "Receptions per game" = recept_pg)
      # 
      # # pivot longer for billboarder plot
      # rank_targ <- rank_targ %>%
      #     pivot_longer(51:52, names_to = "rcpt_str", values_to = "rcpt_val")
      # 
      # # round values to 2 decimals
      # rank_targ$rcpt_val <- round(rank_targ$rcpt_val, 2)
      # 
      # billboarder() %>%
      #     bb_barchart(data = rank_targ,
      #         mapping = bbaes(x = full_name, y = rcpt_val, group = rcpt_str))
      
  } 
  # else if (input$variableDropdown == "Yards per carry") {
  #     df1 <- season()
  #     df2 <- player1()
  #     
  #     rank_ypc <- df1 %>%
  #         filter(position == df2$position[1]) %>%
  #         filter(week >= input$weekRange[1], week <= input$weekRange[2]) %>%
  #         # filter(week >= 1, week <= 16) %>%
  #         group_by(player_id) %>%
  #         add_count() %>%
  #         mutate(rush_yards_pg = (sum(rushing_yards)/nrow(.)),
  #                recieve_yards_pg = (sum(receiving_yards)/nrow(.)),
  #                pass_yards_pg = (sum(passing_yards)/nrow(.)),
  #                tot_fpts = sum(fpts_hppr),
  #                tot_tds = sum(rushing_tds) + sum(passing_tds) + sum(receiving_tds) + sum(special_teams_tds),
  #                tot_recept = sum(receptions),
  #                tot_targ = sum(targets),
  #                tot_carries = sum(carries),
  #                tot_touch = tot_recept+ tot_carries,
  #                fpts_pg = (sum(fpts_hppr)/n),
  #                tot_tds = sum(rushing_tds) + sum(passing_tds) + sum(receiving_tds) + sum(special_teams_tds),
  #                tot_recept = sum(receptions),
  #                tot_targ = sum(targets),
  #                targ_pg = tot_targ/n,
  #                recept_pg = tot_recept/n,
  #                avg_dot = receiving_air_yards/targets,
  #                carries_pg = tot_carries/n,
  #                airyards_pg = sum(receiving_air_yards)/n,
  #                fpts_pt = fpts_pg/(recept_pg + carries_pg),
  #                yards_pg = (sum(rushing_yards) + sum(receiving_yards) + sum(passing_yards))/n,
  #                passyards_pg = sum(passing_yards)/n,
  #                td_int_ratio = sum(passing_tds)/sum(interceptions),
  #                ypc = sum(rushing_yards)/tot_carries,
  #                fpts_per_touch = tot_fpts/(tot_recept + tot_carries)) %>%
  #         ungroup() %>%
  #         filter(carries_pg >= 6.25) %>%
  #         group_by(player_id) %>%
  #         slice(n = 1) %>%
  #         ungroup() %>%
  #         mutate(avg_ypc = mean(ypc)) %>%
  #         arrange(-ypc) %>%
  #         slice(n = 1:36)
  #       
  #       rank_ypc <- rename(rank_ypc, "Fantasy points per touch" = fpts_per_touch, "Yards per carry" = ypc)
  #       rank_ypc <- rank_ypc %>%
  #         pivot_longer(64:65, names_to = "fpts_touch_str", values_to = "fpts_touch_val")
  #       
  #       billboarder() %>%
  #         bb_barchart(data = rank_ypc,
  #                     mapping = bbaes(x = full_name, y = fpts_touch_val, group = fpts_touch_str))
  # }
})
  
output$leagueRankGraph <- renderHighchart({
   leagueRankData()
  })
```

### Data table
```{r}
DTOutput("seasonDT")
```

```{r context="server"}
output$playerSelector <- renderUI({
  df <- season()
   selectInput("playerSearch", "Choose name:",
               as.list(df$full_name),
               multiple= FALSE,
               selectize = TRUE)
})

seasonData <- eventReactive(input$submitButton, {
    df <- season()
    if (input$positionDropdown != "All") {
          df <- df[df$position == input$positionDropdown,]
          }
    #select position, team, full_name to join with summarized df
        df2 <- df %>%
          select(3, 4, 42, 43)
        df2 <- unique(df2)
        df <- df %>%
            group_by(full_name) %>%
            summarise(across(6:39, sum))
        df <- left_join(df2, df, by = "full_name")
        df <- df %>%
          select(4, 1:3, 38, 37, 36, 5:35) %>%
          arrange(-fpts_hppr)
        
    # datatabale
      datatable(df, options = list(scrollX = TRUE, paging = TRUE, searching = TRUE))
  })

output$seasonDT <- renderDT({
   seasonData()
  })
# observeEvent(input$submitButton, {
#   season$df_data <- load_data(as.numeric(input$seasonDropdown))
#              })
```
