---
title: "Fantasy land"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { icon: "fa-question-circle", href: "https://water.noaa.gov/about/nwm", align: right }
    theme: cerulean
    orientation: Rows
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(shiny)
library(flexdashboard)
library(shinyWidgets)
library(shinycustomloader)

library(nflfastR)
library(DT)
library(plotly)

library(ggplot2)
library(dplyr)
library(tidyr)
library(DT)
library(plotly)
library(highcharter)
library(billboarder)

source('helper.R')

# df1 <- load_data(2020)
```

```{r context="server"}

 # season <<- reactive({
     # season <- load_data(as.numeric(input$seasonDropdown))
 # })
# season <- reactiveValues()
season <<- reactive({
  dataset <- load_data(as.numeric(input$seasonDropdown))
})

player1 <- reactive({
  df2 <- get_player_data(season(), input$playerSearch, input$weekRange[1], input$weekRange[2])
})
```

Player stats {data-icon="fa-tint"}
====================================

Inputs {.sidebar}
-------------------------------------

### Filters
```{r}
# dqshiny::autocomplete_input("auto", "Search for a County:",
#                                 value = "",
#                                 max_options = 5,
#                                 options = list(season()$full_name))

selectInput("seasonDropdown",
            label = "Season", 
            choices = c("All", 2020:1999))

selectInput("positionDropdown",
            label = "Position", 
            choices = c("All", "QB", "RB", "WR", "TE"))

uiOutput("playerSelector")

# uiOutput("variableSelect")

# Input: Specification of range within an interval ----
sliderInput("weekRange", "Week",
                  min = 1, max = 16,
                  value = c(1, 16))

verbatimTextOutput("seasonDropdownText")

verbatimTextOutput("positionDropdownText")

verbatimTextOutput("playerSearchText")

verbatimTextOutput("weekRangeText")
```

```{r context = "server"}
# TESTING INPUTS + ACTION BUTTON REACTIVITY
seasonText <- eventReactive(input$submitButton, {
    paste0("Season: ", input$seasonDropdown)
  })

output$seasonDropdownText <- renderText({
   seasonText()
  })

positionText <- eventReactive(input$submitButton, {
    paste0("Position: ", input$positionDropdown)
  })
  
output$positionDropdownText <- renderText({
   positionText()
  })

playerText <- eventReactive(input$submitButton, {
    paste0("Player: ", input$playerSearch)
  })
  
output$playerSearchText <- renderText({
   playerText()
  })

weekRangeText <- eventReactive(input$submitButton, {
    paste0("Week: ", input$weekRange[1], input$weekRange[2])
  })
  
output$weekRangeText <- renderText({
   weekRangeText()
  })
```

### **Submit**
```{r}
shiny::actionButton("submitButton", label = "Enter", icon("search"))
```

Row
----------------------------------------
### Position rank
```{r}
valueBoxOutput("positionRankBox")
```

### FPTS/game value
```{r}
valueBoxOutput("fppgBox")
```

### FPTS/game
```{r}
gaugeOutput("fppgGauge")
```
 
```{r context="server"}
# Total FPTS positional rank during period
positionRank <- eventReactive(input$submitButton, {
  if(is.null(input$playerSearch)) {
      NULL
  } else {
      # df <- season()
      # df <- get_player_data(df, input$playerSearch, input$weekRange[1], input$weekRange[2])
    df1 <- season()
    df2 <- player1()
  # find position rank --- total fpts during period
    ranks <- df1 %>%
      filter(position == df2$position[1]) %>%
      filter(week >= input$weekRange[1], week <= input$weekRange[2]) %>%
      group_by(player_id) %>%
      add_count() %>%
      mutate(total_fpts = sum(fpts_hppr),
             total_tds = sum(rushing_tds) + sum(passing_tds) + sum(receiving_tds),
             fpts_pg = total_fpts/n) %>%
      slice(n = 1) %>%
      arrange(-total_fpts) %>%
      ungroup() %>%
      mutate(rank = 1:n()) %>% 
      filter(player_id == df2$player_id[1]) %>%
      select(rank)
      # select(1:5, 39:47, 6:38)
  }
})

# Output position Rank value box to UI
output$positionRankBox <- renderValueBox({
  valueBox(positionRank(), 
           caption = "Positional rank")
})
```


```{r context="server"}
# FPTS/Game number during period
fppgValue <- eventReactive(input$submitButton, {
  if(is.null(input$playerSearch)) {
      NULL
  } else {
      df1 <- season()
      df2 <- player1()
  # find position rank --- total fpts during period
      ranks <- df1 %>%
        filter(position == df2$position[1]) %>%
        filter(week >= input$weekRange[1], week <= input$weekRange[2]) %>%
        group_by(player_id) %>%
        add_count() %>%
        mutate(total_fpts = sum(fpts_hppr),
               total_tds = sum(rushing_tds) + sum(passing_tds) + sum(receiving_tds),
               fpts_pg = total_fpts/n) %>%
        slice(n = 1) %>%
        arrange(-fpts_pg) %>%
        ungroup() %>%
        mutate(rank = 1:n()) %>%
        filter(player_id == df2$player_id[1]) %>%
        select(fpts_pg) %>% 
        round(2)
  }
})

# Output position Rank value box to UI
output$fppgBox <- renderValueBox({
  valueBox(fppgValue(), 
           caption = "FPTS/game")
})
```

```{r}
fppgGaugeValue <- eventReactive(input$submitButton, {
  if(is.null(input$playerSearch)) {
      NULL
  } else {
      df1 <- season()
      df2 <- player1()
  # find position rank --- total fpts during period
      ranks <- df1 %>%
        filter(position == df2$position[1]) %>%
        filter(week >= input$weekRange[1], week <= input$weekRange[2]) %>%
        group_by(player_id) %>%
        add_count() %>%
        mutate(total_fpts = sum(fpts_hppr),
               total_tds = sum(rushing_tds) + sum(passing_tds) + sum(receiving_tds),
               fpts_pg = total_fpts/n) %>%
        slice(n = 1) %>%
        arrange(-fpts_pg) %>%
        ungroup() %>%
        # mutate(rank = 1:n()) %>%
        # filter(player_id == df2$player_id[1]) %>%
        # select(fpts_pg) %>% 
        # round(2)
        filter(n >= 5) %>% 
        mutate(rank = 1:n(),
               max = max(fpts_pg),
               med = median(fpts_pg),
               min = min(fpts_pg)) %>%
        filter(player_id == df2$player_id[1]) %>%
        select(fpts_pg, min, max, med) %>%
        round(2)
  }
})

output$fppgGauge <- renderGauge({
  df <- fppgGaugeValue()
  
  gauge(df$fpts_pg, min = 0, max = df$max,
  #       gaugeSectors(
  # success = c(16, 35),
  # warning = c(11, 15),
  # danger = c(0, 10)))
  # gauge(df[1], min = df[2], max = df[3],
        gaugeSectors(
  success = c(df$med, df$max),
  warning = c(((df$med - df$min)/2 + 1), (df$med-1)),
  danger = c(df$min, ((df$med - df$min)/2))))
})
```


Row {.tabset}
----------------------------------------
### Yards/FPTS game log
```{r}
plotlyOutput("playerGraph")
```

### Targets/receptions 
```{r}
billboarderOutput('targetsGraph')
```

```{r context="server"}
playerData <- eventReactive(input$submitButton, {
  if(is.null(input$playerSearch)) {
    NULL
  } else {
    df <- season()
    df <- get_player_data(df, input$playerSearch, input$weekRange[1], input$weekRange[2])
    make_player_plot(df)
  }
})

output$playerGraph <- renderPlotly({
  playerData()
})

targetData <- eventReactive(input$submitButton, {
  if(is.null(input$playerSearch)) {
    NULL
  } else {
      df <- season()
      df1 <- get_player_data(df, input$playerSearch, input$weekRange[1], input$weekRange[2])
# pivot longer for billboarder plot
      df1 <- df1 %>%
        pivot_longer(29:28, names_to = "rcpt_str", values_to = "rcpt_val")

      billboarder() %>%
        bb_barchart(data = df1,
                    mapping = bbaes(x = week, y = rcpt_val, group = rcpt_str))
  }
})

output$targetsGraph <- renderBillboarder({
  targetData()
})
```


Row {.tabset}
------------------------------------
### FPTS position Ranking
```{r}
billboarderOutput("positionRankGraph")
```

### Targets/receptions Ranking
```{r}
billboarderOutput('targetsRankGraph')
```

```{r context = "server"}
posRankData <- eventReactive(input$submitButton, {
  if(is.null(input$playerSearch)) {
    NULL
  } else {
      df1 <- season()
      df2 <- player1()
  
      rank_fpts <- df1 %>%
          filter(position == df2$position[1]) %>%
          filter(week >= input$weekRange[1], week <= input$weekRange[2]) %>%
          group_by(player_id) %>%
          add_count() %>%
          mutate(tot_fpts = sum(fpts_hppr),
                 tot_tds = sum(rushing_tds) + sum(passing_tds) + sum(receiving_tds) + sum(special_teams_tds),
                 tot_recept = sum(receptions),
                 tot_targ = sum(targets),
                 fpts_pg = tot_fpts/n,
                 targ_pg = tot_targ/n,
                 recept_pg = tot_recept/n) %>%
          slice(n = 1) %>%
          arrange(-fpts_pg) %>%
          ungroup() %>%
          filter(n >= 5) %>%
          slice(n = 1:24)
      rank_fpts$fpts_pg <- round(rank_fpts$fpts_pg, 2)
    
      billboarder() %>%
          bb_barchart(data = rank_fpts,
              mapping = bbaes(x = full_name, y = fpts_pg))
    }
})

output$positionRankGraph <- renderBillboarder({
        posRankData()
      })

targetRankData <- eventReactive(input$submitButton, {
  if(is.null(input$playerSearch)) {
    NULL
  } else {
      df1 <- season()
      df2 <- player1()
      
      rank_targ <- df1 %>%
          filter(position == df2$position[1]) %>%
          filter(week >= input$weekRange[1], week <= input$weekRange[2]) %>%
          group_by(player_id) %>%
          add_count() %>%
          mutate(tot_fpts = sum(fpts_hppr),
                 tot_tds = sum(rushing_tds) + sum(passing_tds) + sum(receiving_tds) + sum(special_teams_tds),
                 tot_recept = sum(receptions),
                 tot_targ = sum(targets),
                 fpts_pg = tot_fpts/n,
                 targ_pg = tot_targ/n,
                 recept_pg = tot_recept/n) %>%
          slice(n = 1) %>%
          arrange(-recept_pg) %>%
          ungroup() %>%
          mutate(rank = 1:n(),
                 max = max(recept_pg),
                 med = median(recept_pg),
                 min = min(recept_pg)) %>%
          slice(n = 1:24)
    
      # pivot longer for billboarder plot
      rank_targ <- rank_targ %>%
          pivot_longer(50:51, names_to = "rcpt_str", values_to = "rcpt_val")
      # round values to 2 decimals
      rank_targ$rcpt_val <- round(rank_targ$rcpt_val, 2)

      billboarder() %>%
          bb_barchart(data = rank_targ,
              mapping = bbaes(x = full_name, y = rcpt_val, group = rcpt_str))
    }
})

output$targetsRankGraph <- renderBillboarder({
        targetRankData()
      })
```

### Data table
```{r}
DTOutput("seasonDT")
```

```{r context="server"}
output$playerSelector <- renderUI({
  df2 <- season()
   selectInput("playerSearch", "Choose name:", 
               as.list(df2$full_name),
               multiple= FALSE,
               selectize = TRUE)
})

# output$variableSelect <- renderUI({
#       df2 <- season()
#       selectInput(inputId = "variableSelect",
#                   label = "Select target variable",
#                   choices = as.list(names(df2)), 
#                   multiple= FALSE,
#                   selectize = TRUE)
#     })
seasonData <- eventReactive(input$submitButton, {
    df <- season()
    if (input$positionDropdown != "All") {
          df <- df[df$position == input$positionDropdown,]
          }
    #select position, team, full_name to join with summarized df
        df2 <- df %>%
          select(3, 4, 42, 43)
        df2 <- unique(df2)
        df <- df %>%
            group_by(full_name) %>%
            summarise(across(6:39, sum))
        df <- left_join(df2, df, by = "full_name")
        df <- df %>%
          select(4, 1:3, 38, 37, 36, 5:35) %>%
          arrange(-fpts_hppr)
        
    # datatabale
      datatable(df, options = list(scrollX = TRUE, paging = TRUE, searching = TRUE))
  })

output$seasonDT <- renderDT({
   seasonData()
  })
# observeEvent(input$submitButton, {
#   season$df_data <- load_data(as.numeric(input$seasonDropdown))
#              })
```
